inherit_from:
  - .rubocop_todo.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml
  - config/rubocop/rubocop.yml

# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
AllCops:
  TargetRubyVersion: 3.4.1
