inherit_from:
  - .rubocop_todo.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml
  - config/rubocop/rubocop.yml

# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
AllCops:
  TargetRubyVersion: 3.4.1

require:
  - ./lib/rubocop/rails/schema_loader/schema.rb
  - ./lib/rubocop/rails/schema_loader.rb

# 配列で%記法を使用する
Style/WordArray:
  Enabled: true
  MinSize: 0

Style/SymbolArray:
  Enabled: true
  MinSize: 0
