source 'https://rubygems.org'

# ruby '3.4.1'

# レスポンスJSONを制御する[https://github.com/rails-api/active_model_serializers]
gem 'active_model_serializers'
# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 8.0.1'
# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.5'
# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 5.0'
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem 'bcrypt', '~> 3.1.7'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[ windows jruby ]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem 'solid_cache'
gem 'solid_queue'
gem 'solid_cable'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem 'kamal', require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem 'thruster', require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem 'rack-cors'

# ユーザー認証を提供[https://github.com/heartcombo/devise]
gem 'devise'

# deviseを日本語化する[https://github.com/tigrish/devise-i18n]
gem 'devise-i18n'

# ユーザーのトークン認証を提供する[https://github.com/lynndylanhurley/devise_token_auth]
gem 'devise_token_auth'

group :development, :test do
  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem 'brakeman', require: false

  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[ mri windows ], require: 'debug/prelude'

  # https://github.com/thoughtbot/factory_bot
  gem 'factory_bot_rails'

  # ダミーデータ生成[https://github.com/faker-ruby/faker]
  gem 'faker'

  # メール送信をテストする[https://github.com/fgrehm/letter_opener_web]
  gem 'letter_opener_web'

  # デバッグツール pryコンソールを使えるようにする
  # [https://github.com/deivid-rodriguez/pry-byebug]
  gem 'pry-byebug'
  # [https://github.com/pry/pry-doc]
  gem 'pry-doc'
  # [https://github.com/pry/pry-rails]
  gem 'pry-rails'

  # DBスキーマ管理[https://github.com/ridgepole/ridgepole]
  gem 'ridgepole'

  # https://github.com/rspec/rspec-rails
  gem 'rspec-rails'

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem 'rubocop-rails-omakase', require: false
end

group :development do
  # rubocop
  # https://github.com/rubocop/rubocop
  gem 'rubocop', require: false

  # https://github.com/rubocop/rubocop-performance
  gem 'rubocop-performance', require: false

  # https://github.com/rubocop/rubocop-rails
  gem 'rubocop-rails', require: false

  # https://github.com/rubocop/rubocop-rspec
  gem 'rubocop-rspec', require: false

  # RSpec実行高速化[https://github.com/jonleighton/spring-commands-rspec]
  gem 'spring-commands-rspec'

  group :test do
    # [https://matchers.shoulda.io/docs/v5.3.0/]
    gem 'shoulda-matchers', '~> 5.0'
  end
end
